name: Auto Add to Project
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  projectFiles:
    name: Project File Quality
    uses: brobeson/SupportFileQuality/.github/workflows/support_files.yaml@v1
